[global]
map_size = [1200, 700]

[[planet]]
id = "startL"
loc = [100, 350]
owner = 1
[[planet]]
id = "upL"
loc = [300, 200]
edges = ["startL"]
[[planet]]
id = "downL"
loc = [300, 500]
edges = ["startL"]

[[planet]]
id = "upM"
loc = [600, 100]
edges = ["upL"]
[[planet]]
id = "downM"
loc = [600, 600]
edges = ["downL"]
[[planet]]
id = "midM"
loc = [600, 350]
edges = ["upM", "downM"]

[[planet]]
id = "upR"
loc = [900, 200]
edges = ["upM"]
[[planet]]
id = "downR"
loc = [900, 500]
edges = ["downM"]
[[planet]]
id = "startR"
loc = [1100, 350]
owner = 2
edges = ["upR", "downR"]